"""
SQLite persistence for chat history.

Replaces relying on LangGraph's in-memory MemorySaver for durability: that
checkpointer only lives as long as the backend process does, so a restart
would wipe every conversation. This module persists the full, display-ready
transcript (both RAG and Agent turns) per thread_id to disk, independent of
the agent's own internal graph state.

No login: a thread_id is a random UUID generated by the frontend and stored
in the browser's localStorage. Knowing the id is the only "credential" —
this is the practical, no-account trade-off discussed and accepted for this
project, not a substitute for real auth.
"""

from __future__ import annotations

import json
import sqlite3
import uuid
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

DB_PATH = Path(__file__).resolve().parent / "chat_history.db"

SCHEMA = """
CREATE TABLE IF NOT EXISTS threads (
    thread_id   TEXT PRIMARY KEY,
    title       TEXT NOT NULL,
    created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    thread_id   TEXT NOT NULL,
    role        TEXT NOT NULL,       -- 'user' | 'assistant'
    content     TEXT NOT NULL,
    source      TEXT,                -- 'rag' | 'agent' | 'both' | NULL (user turns)
    citations   TEXT,                -- JSON string, RAG doc citations if any
    created_at  TEXT NOT NULL,
    FOREIGN KEY (thread_id) REFERENCES threads (thread_id)
);
"""


@contextmanager
def _conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def init_db() -> None:
    with _conn() as conn:
        conn.executescript(SCHEMA)


def new_thread_id() -> str:
    return str(uuid.uuid4())


def ensure_thread(thread_id: str, title_hint: str = "New chat") -> None:
    with _conn() as conn:
        row = conn.execute("SELECT thread_id FROM threads WHERE thread_id = ?", (thread_id,)).fetchone()
        if row is None:
            conn.execute(
                "INSERT INTO threads (thread_id, title, created_at) VALUES (?, ?, ?)",
                (thread_id, title_hint[:60], datetime.now(timezone.utc).isoformat()),
            )


def add_message(thread_id: str, role: str, content: str, source: Optional[str] = None,
                 citations: Optional[str] = None) -> None:
    with _conn() as conn:
        conn.execute(
            "INSERT INTO messages (thread_id, role, content, source, citations, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?)",
            (thread_id, role, content, source, citations, datetime.now(timezone.utc).isoformat()),
        )


def get_messages(thread_id: str) -> List[dict]:
    with _conn() as conn:
        rows = conn.execute(
            "SELECT role, content, source, citations, created_at FROM messages "
            "WHERE thread_id = ? ORDER BY id ASC",
            (thread_id,),
        ).fetchall()
        messages = [dict(r) for r in rows]
        # citations is stored as a JSON string column -- deserialise it back
        # into a real list/None before it reaches the frontend, which expects
        # to .map() over it directly.
        for m in messages:
            raw = m.get("citations")
            if raw:
                try:
                    m["citations"] = json.loads(raw)
                except (TypeError, ValueError):
                    m["citations"] = None
            else:
                m["citations"] = None
        return messages


def list_threads(thread_ids: List[str]) -> List[dict]:
    """List only the threads the caller already knows the id for (the
    frontend's own localStorage list) — there is no global listing, since
    there is no login to scope one to."""
    if not thread_ids:
        return []
    with _conn() as conn:
        placeholders = ",".join("?" for _ in thread_ids)
        rows = conn.execute(
            f"SELECT thread_id, title, created_at FROM threads WHERE thread_id IN ({placeholders})",
            thread_ids,
        ).fetchall()
        threads = {r["thread_id"]: dict(r) for r in rows}

        for tid in thread_ids:
            last = conn.execute(
                "SELECT content, created_at FROM messages WHERE thread_id = ? AND role = 'user' "
                "ORDER BY id DESC LIMIT 1",
                (tid,),
            ).fetchone()
            if tid in threads and last:
                threads[tid]["preview"] = last["content"][:80]
                threads[tid]["last_at"] = last["created_at"]

        ordered = [threads[tid] for tid in thread_ids if tid in threads]
        ordered.sort(key=lambda t: t.get("last_at", t["created_at"]), reverse=True)
        return ordered


def set_title_from_first_message(thread_id: str, message: str) -> None:
    with _conn() as conn:
        row = conn.execute(
            "SELECT COUNT(*) as c FROM messages WHERE thread_id = ? AND role = 'user'", (thread_id,)
        ).fetchone()
        if row["c"] <= 1:
            conn.execute("UPDATE threads SET title = ? WHERE thread_id = ?", (message[:60], thread_id))
